### PR TITLE
Contest client

### LINKED ISSUE #4: API contest client
An application program interface used to retrieve and post data to the database related to the contests from the past, present, future, and solutions for questions related to a contest.

### PR DESCRIPTION
**Pull request by NamanZelawat**
Fixes #4 added updating status feature.

### CODE REVIEW

**Comment by nveenjain** [comment]
Build is failing... Can you run ```eslint --fix``` and see if it fixes your code or not...

**Comment by NamanZelawat** [comment]
yes sir doing and sending again

**Comment by NamanZelawat** [comment]
Please review the schema of groups as some files are included but not exported which are preventing Travis builds from passing.

**Comment by NamanZelawat** [comment]
https://github.com/Cyber-Labs/online-judge/blob/master/backend/Schema/groups/groups.js
nothing was exported.

**Pull request merged**
